<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Content;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $imageCounter = 1;
        $contents = [
            // Featured Content
            [
                'title' => 'The Dark Knight Rises',
                'description' => 'Eight years after the Joker\'s reign of chaos, Batman is coerced out of exile with the assistance of the mysterious Selina Kyle.',
                'type' => 'movie',
                'genre' => 'Action',
                'thumbnail' => "https://picsum.photos/400/600?random={$imageCounter}",
                'poster' => "https://picsum.photos/800/1200?random={$imageCounter}",
                'banner' => "https://picsum.photos/1920/1080?random={$imageCounter}",
                'release_year' => 2012,
                'duration' => 165,
                'rating' => 8.4,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => true,
                'is_top_pick' => true,
                'view_count' => 1500000,
            ],
            [
                'title' => 'Stranger Things',
                'description' => 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces.',
                'type' => 'series',
                'genre' => 'Horror',
                'thumbnail' => 'https://picsum.photos/400/600?random=3',
                'poster' => 'https://picsum.photos/800/1200?random=3',
                'banner' => 'https://picsum.photos/1920/1080?random=3',
                'release_year' => 2016,
                'duration' => 60,
                'rating' => 8.7,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 2000000,
            ],
            // Trending Now
            [
                'title' => 'Inception',
                'description' => 'A skilled thief is given a chance at redemption if he can complete an impossible task: inception.',
                'type' => 'movie',
                'genre' => 'Sci-Fi',
                'thumbnail' => 'https://picsum.photos/400/600?random=10',
                'poster' => 'https://picsum.photos/800/1200?random=10',
                'banner' => 'https://picsum.photos/1920/1080?random=10',
                'release_year' => 2010,
                'duration' => 148,
                'rating' => 8.8,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 1200000,
            ],
            [
                'title' => 'The Matrix',
                'description' => 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
                'type' => 'movie',
                'genre' => 'Action',
                'thumbnail' => 'https://picsum.photos/400/600?random=11',
                'poster' => 'https://picsum.photos/800/1200?random=11',
                'banner' => 'https://picsum.photos/1920/1080?random=11',
                'release_year' => 1999,
                'duration' => 136,
                'rating' => 8.7,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 1800000,
            ],
            [
                'title' => 'Interstellar',
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'type' => 'movie',
                'genre' => 'Sci-Fi',
                'thumbnail' => 'https://picsum.photos/400/600?random=12',
                'poster' => 'https://picsum.photos/800/1200?random=12',
                'banner' => 'https://picsum.photos/1920/1080?random=12',
                'release_year' => 2014,
                'duration' => 169,
                'rating' => 8.6,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 1400000,
            ],
            [
                'title' => 'Game of Thrones',
                'description' => 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant.',
                'type' => 'series',
                'genre' => 'Fantasy',
                'thumbnail' => 'https://picsum.photos/400/600?random=13',
                'poster' => 'https://picsum.photos/800/1200?random=13',
                'banner' => 'https://picsum.photos/1920/1080?random=13',
                'release_year' => 2011,
                'duration' => 57,
                'rating' => 9.3,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 2500000,
            ],
            [
                'title' => 'Breaking Bad',
                'description' => 'A high school chemistry teacher turned methamphetamine manufacturer partners with a former student.',
                'type' => 'series',
                'genre' => 'Drama',
                'thumbnail' => 'https://picsum.photos/400/600?random=14',
                'poster' => 'https://picsum.photos/800/1200?random=14',
                'banner' => 'https://picsum.photos/1920/1080?random=14',
                'release_year' => 2008,
                'duration' => 49,
                'rating' => 9.5,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 2200000,
            ],
            [
                'title' => 'The Avengers',
                'description' => 'Earth\'s mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.',
                'type' => 'movie',
                'genre' => 'Action',
                'thumbnail' => 'https://picsum.photos/400/600?random=15',
                'poster' => 'https://picsum.photos/800/1200?random=15',
                'banner' => 'https://picsum.photos/1920/1080?random=15',
                'release_year' => 2012,
                'duration' => 143,
                'rating' => 8.0,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 1600000,
            ],
            [
                'title' => 'Pulp Fiction',
                'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine.',
                'type' => 'movie',
                'genre' => 'Crime',
                'thumbnail' => 'https://picsum.photos/400/600?random=16',
                'poster' => 'https://picsum.photos/800/1200?random=16',
                'banner' => 'https://picsum.photos/1920/1080?random=16',
                'release_year' => 1994,
                'duration' => 154,
                'rating' => 8.9,
                'language' => 'English',
                'is_trending' => true,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 1300000,
            ],
            // Top Picks
            [
                'title' => 'The Shawshank Redemption',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'type' => 'movie',
                'genre' => 'Drama',
                'thumbnail' => 'https://picsum.photos/400/600?random=20',
                'poster' => 'https://picsum.photos/800/1200?random=20',
                'banner' => 'https://picsum.photos/1920/1080?random=20',
                'release_year' => 1994,
                'duration' => 142,
                'rating' => 9.3,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 1100000,
            ],
            [
                'title' => 'The Godfather',
                'description' => 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
                'type' => 'movie',
                'genre' => 'Crime',
                'thumbnail' => 'https://picsum.photos/400/600?random=21',
                'poster' => 'https://picsum.photos/800/1200?random=21',
                'banner' => 'https://picsum.photos/1920/1080?random=21',
                'release_year' => 1972,
                'duration' => 175,
                'rating' => 9.2,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 1000000,
            ],
            [
                'title' => 'The Crown',
                'description' => 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the 20th century.',
                'type' => 'series',
                'genre' => 'Drama',
                'thumbnail' => 'https://picsum.photos/400/600?random=22',
                'poster' => 'https://picsum.photos/800/1200?random=22',
                'banner' => 'https://picsum.photos/1920/1080?random=22',
                'release_year' => 2016,
                'duration' => 60,
                'rating' => 8.6,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 900000,
            ],
            [
                'title' => 'The Mandalorian',
                'description' => 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
                'type' => 'series',
                'genre' => 'Sci-Fi',
                'thumbnail' => 'https://picsum.photos/400/600?random=23',
                'poster' => 'https://picsum.photos/800/1200?random=23',
                'banner' => 'https://picsum.photos/1920/1080?random=23',
                'release_year' => 2019,
                'duration' => 40,
                'rating' => 8.7,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 1700000,
            ],
            [
                'title' => 'Fight Club',
                'description' => 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much bigger.',
                'type' => 'movie',
                'genre' => 'Drama',
                'thumbnail' => 'https://picsum.photos/400/600?random=24',
                'poster' => 'https://picsum.photos/800/1200?random=24',
                'banner' => 'https://picsum.photos/1920/1080?random=24',
                'release_year' => 1999,
                'duration' => 139,
                'rating' => 8.8,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 950000,
            ],
            [
                'title' => 'The Witcher',
                'description' => 'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world.',
                'type' => 'series',
                'genre' => 'Fantasy',
                'thumbnail' => 'https://picsum.photos/400/600?random=25',
                'poster' => 'https://picsum.photos/800/1200?random=25',
                'banner' => 'https://picsum.photos/1920/1080?random=25',
                'release_year' => 2019,
                'duration' => 60,
                'rating' => 8.2,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => true,
                'view_count' => 1900000,
            ],
            // Continue Watching
            [
                'title' => 'Dune',
                'description' => 'Feature adaptation of Frank Herbert\'s science fiction novel about the son of a noble family trying to avenge his father\'s death.',
                'type' => 'movie',
                'genre' => 'Sci-Fi',
                'thumbnail' => 'https://picsum.photos/400/600?random=30',
                'poster' => 'https://picsum.photos/800/1200?random=30',
                'banner' => 'https://picsum.photos/1920/1080?random=30',
                'release_year' => 2021,
                'duration' => 155,
                'rating' => 8.0,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 800000,
            ],
            [
                'title' => 'House of Cards',
                'description' => 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.',
                'type' => 'series',
                'genre' => 'Drama',
                'thumbnail' => 'https://picsum.photos/400/600?random=31',
                'poster' => 'https://picsum.photos/800/1200?random=31',
                'banner' => 'https://picsum.photos/1920/1080?random=31',
                'release_year' => 2013,
                'duration' => 51,
                'rating' => 8.7,
                'language' => 'English',
                'is_trending' => false,
                'is_featured' => false,
                'is_top_pick' => false,
                'view_count' => 750000,
            ],
        ];

        foreach ($contents as $content) {
            Content::create($content);
        }

        $this->command->info('Content seeded successfully!');
    }
}
